name: mygraphicnovel
favicon: null
layout_spectrum: 0.6585276578553021
typography_spectrum: 0.2377129269298166
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9377105534076691
  lightness: 0.7668960951268673
  saturation: 0.3113435683771968
  rhythmicContrast: 0.6771727118175477
purpose: []
